version: '3'
services:
  redis:
      container_name: redis
      image: "redis:6.2-alpine"
      restart: always
      ports:
        - "6379:6379"
      command: redis-server
      volumes:
        - redis-data:/data
  app:
    container_name: mflix-search-ms
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  redis-data:
    driver: local
